### ISSUE TITLE
If sqlLite empty - crush

### ISSUE THREAD

**Issue by seralekseenko** [assistant-ai/jess#22]
When I make a request and get an error in the process, the console continues to display the word "Thinking". Why doesn't the program just terminate?

The easiest way to reproduce the bug is:

- `git checkout c37af90723f608a11d03046e5e349bca8a946de7`
- `go run main.go dialog -c MyHelth`
- type any question about heth...

And you'll get `Thinking -Error: sql: no rows in result set`
And the next line is infinity `Thinking`.

**Comment by nikkrichko** [comment]
discussed it should be some where in llm client
